
base_model_params:
  package_name: model
  random_state: 42
  target: prediction column

data_source:
  s3_source: data/pathto.csv
  gdrive: data/googledrive

load_data:
  raw_dataset_csv: data/raw/pathto.csv


split_data:
  train_path: data/processed/train_pathto.csv
  test_path: data/processed/test_pathto.csv
  test_size: 0.2

categorical_vars:
  - feature1
  - feature2
  - feature3
  - feature4

numercial_vars:
  - feature1
  - feature2
  - feature3
  - feature4


_vars_to_transform:
  - feature1
  - feature2
  - feature3
  - feature4


features:
  - feature1
  - feature2
  - feature3
  - feature4

  
estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4

saved_model_dir: saved_models


reports:
  params: report/params.json
  scores: report/scores.json

# model_app_dir: saved_models/model.joblib