base_model_params:
  package_name: model
  random_state: 42
  target: is_bad

data_source:
  s3_source: data/pathto.csv
  gdrive: data/googledrive

load_data:
  row_dataset_link: https://s3.amazonaws.com/datarobot_public_datasets/DR_Demo_Lending_Club.csv
  raw_dataset_csv: raw_data.csv


split_data:
  X_train_path: x_train.csv
  y_train_path: y_train.csv
  X_test_path: x_train.csv
  y_test_path: y_train.csv
  test_size: 0.2

categorical_vars:
  - feature1
  - feature2
  - feature3
  - feature4

numercial_vars:
  - feature1
  - feature2
  - feature3
  - feature4


_vars_to_transform:
  - feature1
  - feature2
  - feature3
  - feature4


features:
  - feature1
  - feature2
  - feature3
  - feature4


features_to_drop:
  - feature1
  - feature2
  - feature3
  - feature4

  
estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4

saved_model_dir: saved_models


reports:
  params: report/params.json
  scores: report/scores.json

# model_app_dir: saved_models/model.joblib